# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import rbctl_pb2 as rbctl__pb2


class RBCtlStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Control = channel.unary_unary(
        '/rbctl.RBCtl/Control',
        request_serializer=rbctl__pb2.Command.SerializeToString,
        response_deserializer=rbctl__pb2.ControlResponse.FromString,
        )


class RBCtlServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Control(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RBCtlServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Control': grpc.unary_unary_rpc_method_handler(
          servicer.Control,
          request_deserializer=rbctl__pb2.Command.FromString,
          response_serializer=rbctl__pb2.ControlResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'rbctl.RBCtl', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
